llmsherpa_api_url: "https://readers.llmsherpa.com/api/document/developer/parseDocument?renderFormat=all"
embedding_model_name: "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
llm_model_name: "microsoft/Phi-3-mini-4k-instruct"
collection_name: "specification_book_collection"
specifications_dir: "data/specifications/"
input_data_path: "data/input/"
output_data_path: "data/output/"
chunk_strategy: "sections"
log_level: "INFO"
log_dir: "logs"
chroma_db_dir: "chroma_db"