llmsherpa_api_url: "http://localhost:5010/api/parseDocument?renderFormat=all&useNewIndentParser=yes"
embedding_model_name: "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
llm_model_name: "microsoft/Phi-3-mini-4k-instruct"
collection_name: "specification_book_collection"
specifications_dir: "data/specifications/"
input_data_path: "data/input/"
output_data_path: "data/output/"
chunk_strategy: "chunks"
log_level: "INFO"
log_dir: "logs"
chroma_db_dir: "chroma_db"
model_type: "openai"  # Can be "ollama", "vllm", or "openai"
openai_api_key: "sk-proj-AmnhwU1MeNxrTP3txj0cT3BlbkFJS7qWrSfwy9f0ZLSnFQ8Y"
openai_model_name: "gpt-4o-mini"  # or whichever model you're using
openai_temperature: 0
openai_json_response: true
vllm_model_name: "gpt-3.5-turbo"